#!/usr/bin/env bash

PATH_TO_RBENVHELPERS="${RBENV_DEV_DIR}/rbenvhelpers"

if [ ! ${RBENV_DEV_DIR} ]; then
  echo "Please set RBENV_DEV_DIR in accordance with the README file for rbenvhelpers" >&2
  exit 1
fi

for LIB_DIR in `find ${RBENV_DEV_DIR} -type d -depth 2 | grep lib`; do
  echo ">Copying ${PATH_TO_RBENVHELPERS} to ${LIB_DIR}"
  cp ${PATH_TO_RBENVHELPERS} ${LIB_DIR}
done