#!/usr/bin/env bash

PLUGIN=$1
RBENV_PLUGIN_NAME=rbenv-${PLUGIN}
RBENV_DEV_PLUGIN_DIR=${RBENV_DEV_DIR}/${PLUGIN}
RBENV_DESTINATION_DIR=${HOME}/.rbenv/plugins/${RBENV_PLUGIN_NAME}

UNDERLINE=`tput smul`
NOUNDERLINE=`tput rmul`

if [ -z ${PLUGIN} ]; then
  echo -e "Usage: ${0} ${UNDERLINE}pluginname${NOUNDERLINE}"
  echo -e "This script will deply ${UNDERLINE}pluginname${NOUNDERLINE} to \${RBENV_DESTINATION_DIR}."
  echo -e "This is typically \${HOME}/.rbenv/plugins/${UNDERLINE}pluginname${NOUNDERLINE}."
  exit 1
fi

if [ -z ${RBENV_DEV_DIR} ]; then
  echo "Please set an env variable RBENV_DEV_DIR pointing to programming dir."
  exit 2
fi

if [ ! -d ${RBENV_DEV_DIR} ]; then
  echo "${RBENV_DEV_DIR} isn't a valid directory."
  exit 3
fi

rsync -av ${RBENV_DEV_PLUGIN_DIR}/ ${RBENV_DESTINATION_DIR}
chmod +x $RBENV_DESTINATION_DIR/bin/${RBENV_PLUGIN_NAME}
