#!/usr/bin/env bash

UNDERLINE=`tput smul`
NOUNDERLINE=`tput rmul`
MY_RBENV_ROOT=`rbenv root`

function execute_command_and_restore_directory() {
  COMMANDS=$*

  pushd . > /dev/null
  ${COMMANDS}
  popd > /dev/null
}

#Returns 0 if bundler exists.
#Returns 1 if bundler does not exist.
function bundler_exists() {
  `gem which bundler > /dev/null 2>&1`
  return $?
}

function update_git_repository() {
  GIT_REPOSITORY=$1

  cd ${GIT_REPOSITORY}

  git pull
}